services:
    db:
        image: postgres:${POSTGRES_VERSION:-14.7}
        restart: always
        container_name: retail_data_pg
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_DB: ${POSTGRES_DB:-RetailDataDemo}
        volumes:
            - ./init:/docker-entrypoint-initdb.d
